### ISSUE TITLE
使用http功能 /send_group_msg 中艾特别人 失效

### ISSUE THREAD

**Issue by zzyyyds88** [NapNeko/NapCatDocs#17]
body内容 为 
{
  "group_id": 99****8097,
  "message": [
    {
      "data": {
        "text": "@13****097 机器人启动"
      },
      "type": "text"
    }
  ]
}

测试后，在群中发送的消息为纯文本格式，不能实现艾特的效果

**Comment by Wesley-Young** [comment]
首先，你是否认真阅读了 [OneBot 11 的文档](https://11.onebot.dev)？发送 At 需要特殊的消息段。

其次，提 issue 的位置不正确。如果在修正 body 内容后问题仍然存在，请前往 [NapCatQQ 主仓库](https://github.com/NapNeko/NapCatQQ/) 提交 issue。
