### ISSUE TITLE
[Docs] BootWay 03 教程，loadNapCat.js 语法错误

### ISSUE THREAD

**Issue by Xenapte** [NapNeko/NapCatDocs#41]
[BootWay03-Linux-SemiAuto.md](https://github.com/NapNeko/NapCatDocs/blob/main/docs/zh-CN/guide/boot/shell/BootWay03-Linux-SemiAuto.md):

```
echo 'const fs = require("fs");
const CurrentPath = path.dirname(__filename)
const path = require("path");
```

注意 `CurrentPath` 一行在初始化 `path` 之前就调用了 `path`：

```ReferenceError: Cannot access 'path' before initialization```

调换一下最后两行就能正常运行（怎么感觉 CurrentPath 这一行像是仓促中加上去的 2333，最后也没有以 `;` 结尾，虽说 JS 内这也不是必要的）。

另外想问 xvfb-run 是否支持自定义当前工作目录，`/opt` 毕竟属于系统路径，非 root 用户除非手动调权限外无法访问。目前我是用符号链接，重定向到我非 root 用户运行 napcat 的目录的，但是不清楚有没有什么更好的方案

**Comment by lyw182** [comment]
的确是仓促加上去的，准备提交的时候突然发现，改了一下没检查就上传了
其实可以修改里面的部分代码行做到修改napcat位置，等一下我做个注释上传吧
