### ISSUE TITLE
上报到http服务器中的请求内容为空

### ISSUE THREAD

**Issue by xcy333** [NapNeko/NapCatDocs#71]
版本：V4.2.10
问题：
上报到http服务器中的请求内容为空，下图为配置

![123](https://github.com/user-attachments/assets/ceb2578f-2254-43af-a5ad-06c50d1532ae)

**Comment by MliKiowa** [comment]
你打印下http post body 我测试正常

**Comment by MliKiowa** [comment]
你打印下http post body 我测试正常 且通过ovo框架测试

**Comment by xcy333** [comment]
> 你打印下http post body 我测试正常 且通过ovo框架测试
上报的服务器上打印的request.body是空的，服务是部署在linux服务器上的
Linux VM-4-4-centos 4.18.0-348.7.1.el8_5.x86_64
用的curl -o napcat.sh https://nclatest.znin.net/NapNeko/NapCat-Installer/main/script/install.sh && sudo bash napcat.sh  命令直接安装的
![image](https://github.com/user-attachments/assets/a04473bc-7d32-440b-b392-c2e605e0db05)

**Comment by MliKiowa** [comment]
> > 你打印下http post body 我测试正常 且通过ovo框架测试
> > 上报的服务器上打印的request.body是空的，服务是部署在linux服务器上的
> > Linux VM-4-4-centos 4.18.0-348.7.1.el8_5.x86_64
> > 用的curl -o napcat.sh https://nclatest.znin.net/NapNeko/NapCat-Installer/main/script/install.sh && sudo bash napcat.sh  命令直接安装的
> > ![image](https://private-user-images.githubusercontent.com/51778307/391405691-a04473bc-7d32-440b-b392-c2e605e0db05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTI5ODgsIm5iZiI6MTczMzExMjY4OCwicGF0aCI6Ii81MTc3ODMwNy8zOTE0MDU2OTEtYTA0NDczYmMtN2QzMi00NDBiLWIzOTItYzJlNjA1ZTBkYjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA0MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YmYzODZmMzAxNDJlNTY2ZWM0N2ZjMDVjYTBhODdkYTU0YmE3MzE2Zjc2YWU4NzcxMmU0NDYxYjY4ZWY2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lJER3MG-lZjGPNLvmeFyLcALKS_WOH0BAkD5tEpfbGg)

你进群来
